import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path'; import { GeminiJsonModel } from '../../src/lib/model/json-model';
import { researchInputFingerprint, researchModelInput, researchStageInstruction, validateFrozenResearchProposal, type FrozenResearchInput } from '../../src/dossier/pipeline'; import { adcTokenProvider } from './credentials';
const project=process.env.GCP_PROJECT_ID; if(!project) throw new Error('GCP_PROJECT_ID required');
const specs=[
 ['2070',{jd:'This is an individual contributor role leading through craft and judgment rather than headcount. 10+ years of experience spanning brand and UX/product design required. A strong portfolio is required. Healthcare experience is a strong plus, but not mandatory.',cv:'Senior Vice President who led a 40-person commercial CoE and brand transformation.',expect:['IC operating shape is not HARD_SCREEN','portfolio/experience classification follows entry wording','healthcare plus is PREFERENCE']}],
 ['Schnell',{jd:'Candidates must have 10+ years of property sales, high-value property closures, and developer or consultancy experience.',cv:'Led commercial growth, teams and agency fee books outside property sales.',expect:['property qualifications may be HARD_SCREEN','commercial precedent remains adjacent or transferable']}],
 ['Artificilux',{jd:'Relevant experience in Operations, Project Management or Team Management is required. Lead operations, reduce founder dependency and improve workflows. Compensation: INR 25k–40k.',cv:'Senior executive with commercial and people authority.',expect:['relevant experience may be HARD_SCREEN','role scope is not HARD_SCREEN','compensation is not screening']}],
 ['entry qualification',{jd:'Prior experience in regulated operations is required.',cv:'Relevant regulated operations experience.',expect:['entry qualification may be HARD_SCREEN']}],
 ['IC operating shape',{jd:'Individual contributor role; lead through craft rather than headcount.',cv:'Led a large team.',expect:['operating shape is not HARD_SCREEN']}],
 ['employment conditions',{jd:'Hybrid in Bengaluru. Compensation INR 30k.',cv:'Executive based in Mumbai.',expect:['conditions are not employer screens']}],
 ['core responsibility',{jd:'Own daily operations and improve delivery performance.',cv:'Improved operating workflows.',expect:['responsibility is CORE_CAPABILITY or ENABLER']}],
 ['preference language',{jd:'Healthcare experience is a strong plus, but not mandatory.',cv:'Consumer experience.',expect:['plus language is PREFERENCE']}]
] as const;
function fixture(name:string, data:any):FrozenResearchInput { const capturedAt='2026-09-16T00:00:00.000Z'; const sources:any[]=[{id:`${name}-jd`,plane:'JD',title:name,locator:`probe:${name}`,text:data.jd,capturedAt,attribution:'JOB_POST'},{id:`${name}-cv`,plane:'CANDIDATE',title:'Candidate',locator:`probe:${name}`,text:data.cv,capturedAt,attribution:'CANDIDATE_SUPPLIED'}]; const evidence:any[]=[{id:'JD-1-1',text:data.jd,state:'EXPLICIT',confidence:1,plane:'JD',citations:[{sourceId:sources[0].id,quote:data.jd}],derivedFrom:[]},{id:'CANDIDATE-1-1',text:data.cv,state:'EXPLICIT',confidence:1,plane:'CANDIDATE',citations:[{sourceId:sources[1].id,quote:data.cv}],derivedFrom:[]}]; const f:any={opportunity:{id:name,company:'Probe',title:name},candidate:{name:'Candidate'},sources,evidence,candidateSourceRefs:[{id:sources[1].id,title:'Candidate'}],candidateConflicts:[],acquisition:[],validEvidenceClaimIds:evidence.map(x=>x.id),fields:['companySize','reportingLine','compensation'],fingerprint:''};f.fingerprint=researchInputFingerprint(f);return f; }
const records:any[]=[]; for(const [name,data] of specs){const frozen=fixture(name,data);for(const level of ['MEDIUM','HIGH'] as const){const model=new GeminiJsonModel(project!,adcTokenProvider(),fetch,{model:'gemini-3.5-flash',thinkingLevel:level,maxOutputTokens:24576,timeoutMs:240000});const started=Date.now();let raw:any=null;let error:string|undefined;try{raw=await model.generate(researchStageInstruction,researchModelInput(frozen));}catch(e){error=e instanceof Error?e.message:String(e)}let research:any; if(raw)try{research=validateFrozenResearchProposal(frozen,raw)}catch(e){error=e instanceof Error?e.message:String(e)}records.push({case:name,expected:data.expect,model:model.version,thinkingLevel:level,sharedInputFingerprint:frozen.fingerprint,rawResponse:raw,validation:research?{status:'ACCEPTED',research}:{status:'FAILED',error},latencyMs:Date.now()-started,attemptCount:1});await mkdir('.radar/dossier-runs',{recursive:true});await writeFile('.radar/dossier-runs/research-capability-probe.json',JSON.stringify({records},null,2));}}
console.log(resolve('.radar/dossier-runs/research-capability-probe.json'));