/** Canonical test ownership. Generate TEST_INVENTORY.md; do not edit membership elsewhere. */
export const testGroups = [
  {
    id: "boundary-journeys",
    name: "Four Boundary Journeys (A, B, C, D)",
    description:
      "End-to-end integration across acquisition, semantic policy, decision persistence, and UI rendering",
  },
  {
    id: "ingestion-lineage",
    name: "Canonical Ingestion & Lineage Contracts",
    description:
      "FK integrity, content hashing, version lineage, operational queue crash recovery, and global metric aggregations",
  },
  {
    id: "tenant-security",
    name: "Multi-Tenant & Scope Security Isolation",
    description:
      "Strict tenant isolation, deployment attack-surface checks, and ontology scope resolution",
  },
  {
    id: "serving-pagination",
    name: "Serving Store & Keyset Pagination Invariants",
    description:
      "Feed ordering parity, opaque cursor stability, dossier navigation, and singleflight coalescing",
  },
  {
    id: "staged-dossier-merge-gate",
    name: "Staged Dossier Merge-Gate Integrity",
    description:
      "Exact evaluated identity/scalar attachment, source trust, presentation provenance, and account isolation",
  },
  {
    id: "gate-0-safety",
    name: "Gate 0 Safety Invariants",
    description:
      "Fail-closed profile resolution, non-escalating permissions, canonical verdicts, reproducibility, and durable worker recovery",
  },
  {
    id: "pursuit",
    name: "Pursuit Profile and Evidence Lineage",
    description: "Pursuit host integration, semantic acceptance, approval ledger, and boundaries",
  },
  {
    id: "runtime-release-safety",
    name: "Runtime & Release Safety Regressions",
    description:
      "Canonical candidate truth, worker separation, corpus durability, migration integrity, and release safety",
  },
] as const;

export type TestGroupId = (typeof testGroups)[number]["id"];
/** Ordered ownership rules; unmapped executable changes deliberately select all domains. */
export const sourceOwnership: readonly {
  pattern: RegExp;
  groups: readonly TestGroupId[] | "all";
}[] = [
  { pattern: /^(tests\/TEST_INVENTORY\.md|scripts\/certify\.ts)$/, groups: ["boundary-journeys"] },
  { pattern: /^(docs\/|.*\.md$)/, groups: [] },
  {
    pattern:
      /^(package(-lock)?\.json$|tsconfig|vitest|scripts\/certification\/|tests\/persistence\/lineage_fixture\.ts|tests\/persistence\/migrated-fixture\.ts)/,
    groups: "all",
  },
  {
    pattern: /^(src\/admin\/|src\/lib\/health\/)/,
    groups: ["boundary-journeys", "tenant-security", "runtime-release-safety"],
  },
  {
    pattern: /^(scripts\/deploy\.ts$|scripts\/release\/|\.github\/workflows\/)/,
    groups: ["boundary-journeys", "tenant-security", "runtime-release-safety"],
  },
  {
    pattern: /^(src\/evaluation\/|scripts\/run-(evaluation|dossier).*worker\.ts$)/,
    groups: [
      "boundary-journeys",
      "staged-dossier-merge-gate",
      "gate-0-safety",
      "runtime-release-safety",
    ],
  },
  {
    pattern: /^src\/lib\/model\//,
    groups: [
      "boundary-journeys",
      "tenant-security",
      "staged-dossier-merge-gate",
      "runtime-release-safety",
    ],
  },
  {
    pattern: /^(src\/pursuit\/|scripts\/run-pursuit|src\/data\/sqlite\/migrations\/0(6[5-9]|70)_)/,
    groups: ["pursuit"],
  },
  {
    pattern: /^(src\/lib\/(security|auth)\/|scripts\/scraper\/)/,
    groups: ["boundary-journeys", "tenant-security", "ingestion-lineage"],
  },
  {
    pattern:
      /^(src\/lib\/intelligence\/editorial\/|src\/components\/radar\/opportunity\/|src\/dossier\/)/,
    groups: ["boundary-journeys", "staged-dossier-merge-gate"],
  },
  {
    pattern: /^(src\/acquisition\/|src\/lib\/intelligence\/(extraction|semantic)\/)/,
    groups: ["boundary-journeys", "ingestion-lineage"],
  },
  { pattern: /^src\/data\//, groups: "all" },
  {
    pattern: /^(src\/routes\/|src\/opportunity\/)|opportunity-(service|queries)/,
    groups: ["boundary-journeys", "serving-pagination"],
  },
];
export type TestEntry = {
  file: string;
  domain: string;
  disposition: "KEEP" | "REVIEW";
  certificationGroup: TestGroupId | null;
  standard: boolean;
  full: boolean;
  regression: boolean;
  required: boolean;
};
export const testRegistry: readonly TestEntry[] = [
  {
    file: "tests/acquisition/gate1-pipeline-invariants.test.ts",
    domain:
      "Dynamic work drain, HealthManager FastPath delegation, contentOrigin enforcement, pre-admission dedupe.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/gate2-target-depth.test.ts",
    domain:
      "Canonical geography semantics, fail-narrow portal geo mapping, multi-location variant compilation, source-identity novelty evaluation, and structured SPA extraction.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/golden-recovery-lineage-cohort.test.ts",
    domain:
      "Authoritative golden production lineage cohort from run-1788527028264; verifies canonicalJobId !== cardHash hand-off across 17 recovered records, admission lineage precedence, zero o_... forks, and alias resolution.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/indeed-listing-identity.test.ts",
    domain:
      "Indeed sponsored/direct URL normalization, bounded redirect safety, and stable `jk` canonical identity.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/ingestion-lineage.test.ts",
    domain:
      "Durable source-card/run to exact canonical job/version lineage, retry idempotency, and tenant/run scope isolation.",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/oci-handoff.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/portal-acquisition-reality.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/post-gate3-acquisition-integrity.test.ts",
    domain:
      "Atomic pre-transaction BlobStore write, unconditional enrichment job creation & run binding, complete enrichment fast-path to READY, version identity payload assertion, and authenticated resume validation.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/reset-corpus-fail-closed.test.ts",
    domain:
      "Fail-closed corpus deletion, query error handling, and exact-row invariance on preserved tables.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/retention-and-execution.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/scoped-ingestion.test.ts",
    domain:
      "A shared canonical opportunity is projected only into the authenticated tenant/person's active plan.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/source-payload-provenance.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/acquisition/transfer-session.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/certification/certification-gate-integrity.test.ts",
    domain:
      "Asserts that `npm run certify` runs all mandatory stages, propagates exit codes, and has zero bypasses.",
    disposition: "KEEP",
    certificationGroup: "boundary-journeys",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/certification/journey_c_decision_persistence_to_dto.test.ts",
    domain:
      "Rapid user decision updates idempotently upsert `canonical_decisions` and reflect immediately in Feed DTO.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/certification/journey_d_loader_to_ui_rendering.test.ts",
    domain: "Loader Metrics $\\rightarrow$ Component State & UI Score Resolution.",
    disposition: "KEEP",
    certificationGroup: "boundary-journeys",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/certification/test-inventory-audit.test.ts",
    domain:
      "Mechanically verifies that all test files and script categories in this inventory exist and are classified.",
    disposition: "KEEP",
    certificationGroup: "boundary-journeys",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/editorial/memo-cockpit-skins.test.ts",
    domain: "Editorial",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/editorial/shortlist-badge-resolution.test.ts",
    domain: "Shortlist badge state resolution (`pursue`, `consider`, `needs more signal`).",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/active-context-resolution.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/attention-gate.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/bedrock-converse-model.test.ts",
    domain:
      "Bedrock Mantle and Converse requests, schema, credential parsing/redaction, and provider failure handling.",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/bedrock-schema.test.ts",
    domain: "Standards-compliant Bedrock JSON Schema projection for dossier contracts.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/candidate-profile-scope.test.ts",
    domain: "Candidate profile persistence and resolution remain strictly tenant/person scoped.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/candidate-projection.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/candidate-truth-boundary.test.ts",
    domain: "Candidate Truth",
    disposition: "KEEP",
    certificationGroup: "runtime-release-safety",
    standard: true,
    full: true,
    regression: false,
    required: true,
  },
  {
    file: "tests/intelligence/canonical-acquisition-integrity.test.ts",
    domain:
      "Multi-portal acquisition payload validation, SHA-256 content hashing, and version lineage.",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/canonical-identity.test.ts",
    domain: "Opt-in live canonical-account audit; never part of deterministic certification.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: false,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/canonical-ingestion-fk-regression.test.ts",
    domain: "Resolves existing `opportunity_versions.id` on conflict; zero orphan foreign keys.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/capability-precedence.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/capability.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/career.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/context-materialization.test.ts",
    domain: "Dossier V2 Materialization",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/corpus-regeneration-worker.test.ts",
    domain: "Runtime Workers",
    disposition: "KEEP",
    certificationGroup: "runtime-release-safety",
    standard: true,
    full: true,
    regression: false,
    required: true,
  },
  {
    file: "tests/intelligence/dossier-grounding.test.ts",
    domain: "Evidence-plane, provenance, and grounded dossier validation invariants.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/dossier-review-queue.test.ts",
    domain: "Durable review / cooldown / leases / withholding",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/dossier-source-authority.test.ts",
    domain: "Immutable source snapshot and source-authority boundary.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/editorial-boundary.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/evaluation-work-scheduler.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/evaluator-control-worker-liveness.test.ts",
    domain: "Runtime Workers",
    disposition: "KEEP",
    certificationGroup: "runtime-release-safety",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/evidence-extraction-bedrock.test.ts",
    domain: "Bedrock source-extraction schema and exact-evidence contract.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/gate4-write-refresh-edge-contract.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/gemini-context-cache.test.ts",
    domain: "Immutable candidate cache / expiry / provider failures",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/identity.test.ts",
    domain:
      "Executive seniority categorization (`C_SUITE`, `VP`), role matching, and theme extraction.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/job-projection-cache.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/job-projection-role-work.test.ts",
    domain:
      "JobProjectionBuilder retains bounded responsibilities and outcomes while excluding qualifications and corporate copy.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/m42-identity-versioning.test.ts",
    domain: "Identity & Candidate Projection",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/m9_2c-posting-date.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/m9_3-decision-write-path.test.ts",
    domain: "Decision Persistence",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/m9_3-decisions-store-client.test.ts",
    domain: "Optimistic UI store synchronization with server functions and rollback on error.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/m9_3-server-boundary.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/m9_3-sync-decisions-reconciliation.test.ts",
    domain: "Decision Persistence",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/m9_4_1-multi-tenant-isolation.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/memo-contract.test.ts",
    domain: "Intelligence",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/metrics-portal-breakdown.test.ts",
    domain:
      "Portal metrics represent full database search plan population, not local page samples.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/model-c-quality.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/phase-c-runtime-separation.test.ts",
    domain: "Runtime Workers",
    disposition: "KEEP",
    certificationGroup: "runtime-release-safety",
    standard: true,
    full: true,
    regression: false,
    required: true,
  },
  {
    file: "tests/intelligence/profile-journey-controls.test.ts",
    domain: "Profile processing, recommendation refresh, and polling controls.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/profile-projection-version-compat.test.ts",
    domain:
      "Legacy profile projections deterministically reproduce the exact context-pinned content version without a latest-row fallback.",
    disposition: "KEEP",
    certificationGroup: "gate-0-safety",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/recommendation-freshness.test.ts",
    domain: "Recommendation freshness follows immutable profile and evaluation context versions.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/schema-contract.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/seniority-integrity.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/serving-contract.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/staged-composition.test.ts",
    domain: "Editorial / Verdict",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/staged-context-input.test.ts",
    domain: "Context / Source Provenance",
    disposition: "KEEP",
    certificationGroup: "boundary-journeys",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/staged-decision.test.ts",
    domain:
      "Typed entry-selection adjudication, candidate mapping, gap classification, and decision-boundary invariants for staged intelligence.",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/staged-production-integration.test.ts",
    domain: "Staged source identity, policy-context isolation, and persistence boundaries.",
    disposition: "KEEP",
    certificationGroup: "boundary-journeys",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/staged-queue-lifecycle.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/staged-screening-authority.test.ts",
    domain: "Staged screening authority and exact-JD evidence boundary.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/intelligence/write-refresh-runtime-correctness.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/ontology/tenant-ontology-compiler.test.ts",
    domain: "Tenant-customized ontology definitions compile and validate within tenant sandboxes.",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/active_pointer_precedence.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/adapter-contracts.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/blob-store-connectivity.test.ts",
    domain:
      "Multi-backend BlobStore connectivity, S3 REST protocol, 404/error handling, and synthetic probe healthCheck.",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/cross-instance-payload-retrieval.test.ts",
    domain:
      "Distributed BlobStore payload retrieval across isolated process/disk instances, missing blob graceful failure.",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/database-safety.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/deployment-determinism.test.ts",
    domain:
      "OpportunityService delegates serving queries exclusively to repos.canonicalServing and DatabaseAdapter with zero filesystem fallbacks.",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/distributed-lease-contention.test.ts",
    domain:
      "Multi-instance concurrent lease mutual exclusion, non-claiming loser invariant, and crash failover.",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/evaluation_context_pointer_trigger.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/evaluation_context_pointers.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/evaluation_pointer_flow.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/m41-canonical-schema.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/m51-queue-schema.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/m61-credential-schema.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/migration-runner.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: "runtime-release-safety",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/oci-blob-store.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/populated-migration.test.ts",
    domain:
      "Populated database migration across 001-043, proving zero foreign key check violations and row identity preservation.",
    disposition: "KEEP",
    certificationGroup: "runtime-release-safety",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/queue-crash-restart.test.ts",
    domain:
      "Turso operational queue crash recovery, idempotency, concurrent lease exclusion, and zero filesystem state.",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/scrape-run-state-machine.test.ts",
    domain:
      "Atomic active run race, cross-tenant/person concurrency, terminal immutability, restart durability.",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/persistence/sqlite-retirement.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/policy/atomic-plan-activation.test.ts",
    domain:
      "Replacing career intent produces a complete, immediately routeable evaluation context or rolls back without stale-plan exposure.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/policy/attention-management.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/policy/eligibility-gates.test.ts",
    domain:
      "Strict evaluation of core eligibility criteria (location, seniority, operating model).",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/policy/indeed-filter.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/policy/opportunity-control-plane.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/policy/policy-invariants.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/policy/pursue-queue-isolation.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/policy/read-economics.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/pursuit/approval-ledger.test.ts",
    domain: "Pursuit evidence approval",
    disposition: "KEEP",
    certificationGroup: "pursuit",
    standard: false,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/pursuit/core-host-integration.test.ts",
    domain: "Pursuit host integration",
    disposition: "KEEP",
    certificationGroup: "pursuit",
    standard: false,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/pursuit/integration-boundaries.test.ts",
    domain: "Pursuit integration boundaries",
    disposition: "KEEP",
    certificationGroup: "pursuit",
    standard: false,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/pursuit/memo-model-benchmark.test.ts",
    domain: "Pursuit live memo model quality/cost benchmark",
    disposition: "KEEP",
    certificationGroup: "pursuit",
    standard: false,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/pursuit/resume-copy.test.ts",
    domain: "Pursuit Execution",
    disposition: "KEEP",
    certificationGroup: null,
    standard: false,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/pursuit/resume-export-presentation.test.ts",
    domain: "Pursuit Execution",
    disposition: "KEEP",
    certificationGroup: null,
    standard: false,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/pursuit/semantic-acceptance.test.ts",
    domain: "Pursuit semantic acceptance",
    disposition: "KEEP",
    certificationGroup: "pursuit",
    standard: false,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/pursuit/thesis-enrichment-integrity.test.ts",
    domain: "Pursuit thesis enrichment integrity",
    disposition: "KEEP",
    certificationGroup: "pursuit",
    standard: false,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/regression/p0-enrichment-extraction-pipeline.test.ts",
    domain: "Evaluation & Policy",
    disposition: "REVIEW",
    certificationGroup: null,
    standard: false,
    full: true,
    regression: true,
    required: false,
  },
  {
    file: "tests/regression/p0-invariant-candidate-level.test.ts",
    domain: "Evaluation & Policy",
    disposition: "REVIEW",
    certificationGroup: null,
    standard: false,
    full: true,
    regression: true,
    required: false,
  },
  {
    file: "tests/regression/p0-invariant-capability-unknown.test.ts",
    domain: "Evaluation & Policy",
    disposition: "REVIEW",
    certificationGroup: null,
    standard: false,
    full: true,
    regression: true,
    required: false,
  },
  {
    file: "tests/regression/stage-3f-comparisons.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: false,
    full: true,
    regression: true,
    required: false,
  },
  {
    file: "tests/regression/stage-3f-hashing.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: false,
    full: true,
    regression: true,
    required: false,
  },
  {
    file: "tests/regression/stage-4b-singleflight.test.ts",
    domain: "Evaluation & Policy",
    disposition: "KEEP",
    certificationGroup: null,
    standard: false,
    full: true,
    regression: true,
    required: false,
  },
  {
    file: "tests/release/artifact-integrity.test.ts",
    domain: "Release Engineering",
    disposition: "KEEP",
    certificationGroup: "runtime-release-safety",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/release/deployment.test.ts",
    domain: "Release Engineering",
    disposition: "KEEP",
    certificationGroup: "runtime-release-safety",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/release/readiness.test.ts",
    domain: "Release Engineering",
    disposition: "KEEP",
    certificationGroup: "runtime-release-safety",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/release/runtime-topology.test.ts",
    domain: "Release Engineering",
    disposition: "KEEP",
    certificationGroup: "runtime-release-safety",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/acquisition-variant-contract.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/acquisition-wait-budget.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/atomic-progress-recovery.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: "ingestion-lineage",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/ats-content-quality.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/ats-content-sanitization.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/ats-jsonld-extraction.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/auth-security.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/enrichment-payload-resolution.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/hard-filter-semantics.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/indeed-acquisition-resilience.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/indeed-jk-provenance.test.ts",
    domain:
      "Strict 16-hex character JK validation, non-JK employer requisition isolation, and fast-fetch ATS direct resolution.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/journal-lifecycle.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/linkedin-rich-discovery-fallback.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/live-test-policy.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/m56-operational-consolidation.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/naukri-cancellation-no-legacy-fetch.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/naukri-hydration-quota.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/naukri-pagination-browser-context.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/naukri-pagination-telemetry.test.ts",
    domain:
      "Non-overlapping work-unit pagination mapping, out-of-bounds rejection, scroll quota accumulation, and telemetry.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/naukri-provenance.test.ts",
    domain:
      "Explicit full-JD provenance flag validation, prevention of length-based inference, and native detail fetch routing.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/naukri-state.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/scheduler-exhaustion-contract.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/scheduler-transport-safety.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/scheduler-yield-separation.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/scrape-progress.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: false,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/scraper-acquisition-contract.test.ts",
    domain:
      "LinkedIn fast hydration & exit, universal sparse preservation (LinkedIn/Naukri), and failure transparency without fake empty results.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/scraper-control.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/scraper-correctness-contract.test.ts",
    domain:
      "Authoritative active-plan resolution, zero fallback/zero units for authenticated runs, and Indeed sparse detail preservation.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/scraper-operability.test.ts",
    domain:
      "Scraper Operability Patch: planless scoped runs truthful returns, migration 046 nullable search plan rebuild, active run partial unique index, machine profile mode/tenant retirement, cross-scope profile isolation & fail-closed rename, atomic legacy migration, fresh vs stale corrupt lock handling, native Chromium UA, single-authority confirmation without TDZ, and DB-free GLOBAL local-only acquisition.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/scraper-smoke.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/scraper/validator.test.ts",
    domain: "Ingestion & Lineage",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/active-tenant-pollution-repair.test.ts",
    domain:
      "Tenant-pollution maintenance repair is exact-ID-only, transactional, read-only by default, and cannot mutate protected identity state.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/admin-config.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: true,
  },
  {
    file: "tests/security/admin-foundations.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: true,
  },
  {
    file: "tests/security/admin-operations.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/document-provider-operations.test.ts",
    domain: "Document provider recovery, ownership, and credential convergence",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/admin-protection.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: true,
  },
  {
    file: "tests/security/admin-taxonomy.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: true,
  },
  {
    file: "tests/security/candidate-profile-tenant-isolation.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: true,
  },
  {
    file: "tests/security/decisions-account-isolation.test.ts",
    domain:
      "Canonical dossier presentation reads and decision updates remain isolated to the authenticated tenant/person identity.",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/deploy-attack-surface-removed.test.ts",
    domain: "Zero app-layer deployment endpoints, firewall flushing, or SSH mutations.",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/evaluation-context-isolation.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: "gate-0-safety",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/evidence-dedup-repository-scope.test.ts",
    domain:
      "Content-hash evidence reuse is scoped to the owning candidate at the repository boundary.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/evidence-ownership-deduplication.test.ts",
    domain: "Defensive evidence graph reuse never transfers ownership across candidates.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/host-provider-recovery.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/m62-credential-vault.test.ts",
    domain: "AES-256 envelope encryption and key rotation for portal scraper credentials.",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: true,
  },
  {
    file: "tests/security/m63-credential-broker.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/m64-scraper-credential-injection.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/m8-tenant-isolation.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/notification-lifecycle.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/oauth-callback-url.test.ts",
    domain:
      "Non-local Google OAuth callback configuration requires an explicit HTTPS redirect URI.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/oauth-http-routes.test.ts",
    domain:
      "OAuth initiation and callback are raw HTTP GET handlers with signed state, PKCE, verified identity, and session boundaries.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/oauth-scope-provisioning.test.ts",
    domain:
      "Verified Google identity provisions one resolvable person, tenant, membership, and OAuth scope atomically.",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: true,
  },
  {
    file: "tests/security/phase13_cross_tenant_pentest.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/scope-resolver-equivalence.test.ts",
    domain:
      "Strict multi-tenant scope isolation: zero data leaks across distinct tenant boundaries.",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/scrape-run-ownership.test.ts",
    domain:
      "Multi-tenant scrape run ownership, negative matrix isolation, cross-tenant abort/progress protection.",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/scrape-tenant-identity.test.ts",
    domain: "Authenticated scraper identity, DB membership RBAC, zero default_tenant fallback.",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/scraper-auth-permission-non-escalation.test.ts",
    domain:
      "Scraper authorization preserves membership grants and never manufactures scraper or credential capabilities.",
    disposition: "KEEP",
    certificationGroup: "gate-0-safety",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/tavily-hardening.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/security/tenant-isolation.test.ts",
    domain: "Security & Tenant Isolation",
    disposition: "KEEP",
    certificationGroup: "tenant-security",
    standard: true,
    full: true,
    regression: false,
    required: true,
  },
  {
    file: "tests/semantic/controlled_integration.test.ts",
    domain: "Semantic Grounding",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/semantic/extraction-sanitation.test.ts",
    domain: "Semantic Grounding",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/semantic/normalization.test.ts",
    domain: "Currency, date, location, and seniority string normalization.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/semantic/ontology.test.ts",
    domain:
      "Comprehensive executive ontology validation (roles, capabilities, industries, seniority).",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/semantic/phase6a1_threshold_boundaries.test.ts",
    domain: "Semantic Grounding",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/semantic/phase6c_production_observability.test.ts",
    domain: "Semantic Grounding",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/semantic/phase6d_production_monitoring.test.ts",
    domain: "Semantic Grounding",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/current-serving-boundary.test.ts",
    domain: "Serving & Pagination",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/cursor.test.ts",
    domain: "Opaque cursor encoding, decoding, validation, and tamper-resistance.",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/decided-population-completeness.test.ts",
    domain:
      "Decided-opportunity retrieval exhausts keyset pages and never hides records after the first 50.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/keyset_pagination.test.ts",
    domain: "Keyset pagination returns deterministic, contiguous pages without duplicate rows.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/navigation-and-shortlist-contract.test.ts",
    domain: "Serving & Pagination",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/opportunity-queries-contract.test.ts",
    domain: "Serving & Pagination",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/route_server_functions_parity.test.ts",
    domain: "Serving & Pagination",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/scraped-job-detail.test.ts",
    domain: "Serving & Pagination",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/singleflight-scope-isolation.test.ts",
    domain:
      "10 concurrent requests coalesce to 1 underlying query; complete tenant, person, and search-plan scope isolation.",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/singleflight_and_observability.test.ts",
    domain: "Singleflight request coalescing prevents duplicate concurrent database queries.",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/sql_feed_parity.test.ts",
    domain: "Serving feed SQL queries match materialized evaluation and user decision states.",
    disposition: "KEEP",
    certificationGroup: null,
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/sql_metrics_aggregation.test.ts",
    domain:
      "Canonical population, engine/user/effective metric partitions reconcile independently; `allRecordedDecisions = userBreakdown.total`.",
    disposition: "KEEP",
    certificationGroup: "serving-pagination",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
  {
    file: "tests/serving/staged-rich-serving.test.ts",
    domain: "Serving & Pagination",
    disposition: "KEEP",
    certificationGroup: "staged-dossier-merge-gate",
    standard: true,
    full: true,
    regression: false,
    required: false,
  },
];

export const standardTestFiles = testRegistry
  .filter((entry) => entry.standard)
  .map((entry) => entry.file);
export const fullTestFiles = testRegistry.filter((entry) => entry.full).map((entry) => entry.file);
export const regressionTestFiles = testRegistry
  .filter((entry) => entry.regression)
  .map((entry) => entry.file);
