/** Resumable staged-v1 backfill: selects and enqueues normal durable worker work only. */
import { getDatabaseAdapter } from '../src/data/database';
import { resolveServingScope } from '../src/lib/security/scope-resolver';
import { SqliteEvaluationContextStore } from '../src/data/sqlite/repositories/SqliteEvaluationContextStore';
import { STAGED_POLICY_VERSION } from '../src/data/sqlite/repositories/SqliteStagedEvaluationStore';
import { EvaluationWorkScheduler } from '../src/lib/intelligence/EvaluationWorkScheduler';

const args=process.argv.slice(2); const option=(name:string)=>{const i=args.indexOf(name);return i>=0?args[i+1]:undefined}; const dryRun=args.includes('--dry-run'); const limit=Math.max(1,Number(option('--limit')||'25')); const requestedJob=option('--job-hash'); const requestedPerson=option('--person-id');
async function main(){
 const db=getDatabaseAdapter(); const personId=requestedPerson || (await db.one<{person_id:string}>(`SELECT person_id FROM active_evaluation_contexts ORDER BY activated_at DESC LIMIT 1`))?.person_id; if(!personId)throw new Error('BACKFILL_SCOPE_UNAVAILABLE');
 const scope=(await resolveServingScope(personId)).scope; const active=await db.one<any>(`SELECT a.search_plan_id,ec.search_plan_snapshot_id,ec.ontology_version,ec.ontology_fingerprint,ec.profile_version FROM active_evaluation_contexts a JOIN evaluation_contexts ec ON ec.context_fingerprint=a.context_fingerprint WHERE a.tenant_id=? AND a.person_id=? ORDER BY a.activated_at DESC LIMIT 1`,[scope.tenantId,personId]); if(!active)throw new Error('BACKFILL_ACTIVE_CONTEXT_UNAVAILABLE');
 const contexts=new SqliteEvaluationContextStore(db); const staged=await contexts.createEvaluationContext(scope,{searchPlanSnapshotId:active.search_plan_snapshot_id,ontologyVersion:active.ontology_version,ontologyFingerprint:active.ontology_fingerprint,policyVersion:STAGED_POLICY_VERSION,profileVersion:active.profile_version});
 await db.execute(`INSERT INTO evaluation_context_scopes(context_fingerprint,tenant_id,person_id,search_plan_id) VALUES(?,?,?,?) ON CONFLICT(context_fingerprint) DO NOTHING`,[staged.contextFingerprint,scope.tenantId,personId,active.search_plan_id]);
 const rows=await db.many<any>(`SELECT spc.canonical_job_id,spc.opportunity_version FROM search_plan_candidates spc JOIN opportunity_versions ov ON ov.canonical_job_id=spc.canonical_job_id AND ov.id=spc.opportunity_version LEFT JOIN staged_evaluations se ON se.tenant_id=spc.tenant_id AND se.person_id=spc.person_id AND se.canonical_job_id=spc.canonical_job_id AND se.opportunity_version=spc.opportunity_version AND se.evaluation_context_fingerprint=? WHERE spc.tenant_id=? AND spc.person_id=? AND spc.search_plan_id=? AND spc.attention_decision='CANDIDATE' AND ov.lifecycle_state='ACTIVE' AND ov.acquisition_status='ACQUIRED' AND se.id IS NULL ${requestedJob?'AND spc.canonical_job_id=?':''} ORDER BY spc.canonical_job_id LIMIT ?`,requestedJob?[staged.contextFingerprint,scope.tenantId,personId,active.search_plan_id,requestedJob,limit]:[staged.contextFingerprint,scope.tenantId,personId,active.search_plan_id,limit]);
 if(dryRun){console.log(JSON.stringify({dryRun:true,eligible:rows.length,alreadyStaged:0,inputProvenanceCheckedAtWorker:true,contextFingerprint:staged.contextFingerprint,items:rows},null,2));return;}
 const scheduler=new EvaluationWorkScheduler(db); const queued=[]; for(const row of rows) queued.push(await scheduler.ensureWork({tenantId:scope.tenantId,personId,searchPlanId:active.search_plan_id,canonicalJobId:row.canonical_job_id,opportunityVersion:row.opportunity_version,evaluationContextFingerprint:staged.contextFingerprint})); console.log(JSON.stringify({dryRun:false,queued:queued.length,contextFingerprint:staged.contextFingerprint,queued},null,2));
}
main().catch(error=>{console.error(error instanceof Error?error.message:'BACKFILL_FAILED');process.exitCode=1});
