/** Display only. Order is a product invariant, not an operator setting. */
export const engineStages = [
  {
    name: "Acquisition",
    kind: "Rule-based",
    input: "Compiled search intent and portal results",
    does: "Preserves source snapshots and queues durable transfer.",
    continues: "Honest, usable source payload → Attention",
    stops: "Portal attention, source integrity or transfer failures",
  },
  {
    name: "Attention",
    kind: "Rule-based",
    input: "Captured source and candidate search intent",
    does: "Checks exclusions, geography and explicit mandate contradictions. Title terminology is indicative.",
    continues: "Admitted and REVIEW cases → Evidence",
    stops: "Explicit exclusions and supported contradictions",
  },
  {
    name: "Evidence",
    kind: "Rules + model",
    input: "Role, candidate and public company sources",
    does: "Extracts evidence, acquires context and preserves claim lineage.",
    continues: "Pinned evidence → Evaluation",
    stops: "Integrity failures; unresolved information becomes a decision hinge",
  },
  {
    name: "Evaluation",
    kind: "Model",
    input: "Pinned role, candidate and context evidence",
    does: "Interprets the mandate, screens requirements, maps fit and derives the canonical verdict.",
    continues: "PURSUE / CONSIDER → Memo; PASS retained as evaluation",
    stops: "Invalid output or source integrity failure",
  },
  {
    name: "Memo",
    kind: "Model",
    input: "Canonical PURSUE / CONSIDER intelligence",
    does: "Composes rich Template B with grounded inference and deliberate narrative variation.",
    continues: "Draft → Factual review",
    stops: "Composition failures; PASS has no memo",
  },
  {
    name: "Factual review",
    kind: "Model + rules",
    input: "Draft and its source evidence",
    does: "Validates claims and distinguishes EXPLICIT from INFERRED.",
    continues: "Reviewed matching memo → Shortlist",
    stops: "Unsupported claims or invalid review",
  },
  {
    name: "Shortlist",
    kind: "Rule-based",
    input: "Reviewed memo and canonical decision",
    does: "Serves eligible PURSUE / CONSIDER dossiers.",
    continues: "Candidate decision → optional Pursuit",
    stops: "Unreviewed or mismatched identity",
  },
  {
    name: "Pursuit",
    kind: "Rules + optional model",
    input: "Candidate pursuit intent and approved evidence",
    does: "Prepares outreach and interview strategy within the pursuit budget.",
    continues: "Prepared pursuit package",
    stops: "Missing evidence, budget or preparation failure",
  },
] as const;
