/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScrapedRouteImport } from './routes/scraped'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaMappingRouteImport } from './routes/qa.mapping'
import { Route as OpportunityJobHashRouteImport } from './routes/opportunity.$jobHash'

const ScrapedRoute = ScrapedRouteImport.update({
  id: '/scraped',
  path: '/scraped',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaMappingRoute = QaMappingRouteImport.update({
  id: '/qa/mapping',
  path: '/qa/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityJobHashRoute = OpportunityJobHashRouteImport.update({
  id: '/opportunity/$jobHash',
  path: '/opportunity/$jobHash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/scraped': typeof ScrapedRoute
  '/opportunity/$jobHash': typeof OpportunityJobHashRoute
  '/qa/mapping': typeof QaMappingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/scraped': typeof ScrapedRoute
  '/opportunity/$jobHash': typeof OpportunityJobHashRoute
  '/qa/mapping': typeof QaMappingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/scraped': typeof ScrapedRoute
  '/opportunity/$jobHash': typeof OpportunityJobHashRoute
  '/qa/mapping': typeof QaMappingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/decisions' | '/scraped' | '/opportunity/$jobHash' | '/qa/mapping'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decisions' | '/scraped' | '/opportunity/$jobHash' | '/qa/mapping'
  id:
    | '__root__'
    | '/'
    | '/decisions'
    | '/scraped'
    | '/opportunity/$jobHash'
    | '/qa/mapping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionsRoute: typeof DecisionsRoute
  ScrapedRoute: typeof ScrapedRoute
  OpportunityJobHashRoute: typeof OpportunityJobHashRoute
  QaMappingRoute: typeof QaMappingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scraped': {
      id: '/scraped'
      path: '/scraped'
      fullPath: '/scraped'
      preLoaderRoute: typeof ScrapedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/mapping': {
      id: '/qa/mapping'
      path: '/qa/mapping'
      fullPath: '/qa/mapping'
      preLoaderRoute: typeof QaMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$jobHash': {
      id: '/opportunity/$jobHash'
      path: '/opportunity/$jobHash'
      fullPath: '/opportunity/$jobHash'
      preLoaderRoute: typeof OpportunityJobHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionsRoute: DecisionsRoute,
  ScrapedRoute: ScrapedRoute,
  OpportunityJobHashRoute: OpportunityJobHashRoute,
  QaMappingRoute: QaMappingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
