/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as ScrapedRouteImport } from './routes/scraped'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FontSandboxRouteImport } from './routes/font-sandbox'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as CorpusRouteImport } from './routes/corpus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaMappingRouteImport } from './routes/qa.mapping'
import { Route as OpportunityJobHashRouteImport } from './routes/opportunity.$jobHash'
import { Route as ApiWebhooksDeployRouteImport } from './routes/api/webhooks/deploy'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapedRoute = ScrapedRouteImport.update({
  id: '/scraped',
  path: '/scraped',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FontSandboxRoute = FontSandboxRouteImport.update({
  id: '/font-sandbox',
  path: '/font-sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusRoute = CorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaMappingRoute = QaMappingRouteImport.update({
  id: '/qa/mapping',
  path: '/qa/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityJobHashRoute = OpportunityJobHashRouteImport.update({
  id: '/opportunity/$jobHash',
  path: '/opportunity/$jobHash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksDeployRoute = ApiWebhooksDeployRouteImport.update({
  id: '/api/webhooks/deploy',
  path: '/api/webhooks/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/decisions': typeof DecisionsRoute
  '/design-system': typeof DesignSystemRoute
  '/font-sandbox': typeof FontSandboxRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/scraped': typeof ScrapedRoute
  '/workbench': typeof WorkbenchRoute
  '/opportunity/$jobHash': typeof OpportunityJobHashRoute
  '/qa/mapping': typeof QaMappingRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/webhooks/deploy': typeof ApiWebhooksDeployRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/decisions': typeof DecisionsRoute
  '/design-system': typeof DesignSystemRoute
  '/font-sandbox': typeof FontSandboxRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/scraped': typeof ScrapedRoute
  '/workbench': typeof WorkbenchRoute
  '/opportunity/$jobHash': typeof OpportunityJobHashRoute
  '/qa/mapping': typeof QaMappingRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/webhooks/deploy': typeof ApiWebhooksDeployRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/decisions': typeof DecisionsRoute
  '/design-system': typeof DesignSystemRoute
  '/font-sandbox': typeof FontSandboxRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/scraped': typeof ScrapedRoute
  '/workbench': typeof WorkbenchRoute
  '/opportunity/$jobHash': typeof OpportunityJobHashRoute
  '/qa/mapping': typeof QaMappingRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/webhooks/deploy': typeof ApiWebhooksDeployRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corpus'
    | '/decisions'
    | '/design-system'
    | '/font-sandbox'
    | '/login'
    | '/profile'
    | '/scraped'
    | '/workbench'
    | '/opportunity/$jobHash'
    | '/qa/mapping'
    | '/api/auth/callback'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/webhooks/deploy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corpus'
    | '/decisions'
    | '/design-system'
    | '/font-sandbox'
    | '/login'
    | '/profile'
    | '/scraped'
    | '/workbench'
    | '/opportunity/$jobHash'
    | '/qa/mapping'
    | '/api/auth/callback'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/webhooks/deploy'
  id:
    | '__root__'
    | '/'
    | '/corpus'
    | '/decisions'
    | '/design-system'
    | '/font-sandbox'
    | '/login'
    | '/profile'
    | '/scraped'
    | '/workbench'
    | '/opportunity/$jobHash'
    | '/qa/mapping'
    | '/api/auth/callback'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/webhooks/deploy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorpusRoute: typeof CorpusRoute
  DecisionsRoute: typeof DecisionsRoute
  DesignSystemRoute: typeof DesignSystemRoute
  FontSandboxRoute: typeof FontSandboxRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ScrapedRoute: typeof ScrapedRoute
  WorkbenchRoute: typeof WorkbenchRoute
  OpportunityJobHashRoute: typeof OpportunityJobHashRoute
  QaMappingRoute: typeof QaMappingRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiWebhooksDeployRoute: typeof ApiWebhooksDeployRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraped': {
      id: '/scraped'
      path: '/scraped'
      fullPath: '/scraped'
      preLoaderRoute: typeof ScrapedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font-sandbox': {
      id: '/font-sandbox'
      path: '/font-sandbox'
      fullPath: '/font-sandbox'
      preLoaderRoute: typeof FontSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus': {
      id: '/corpus'
      path: '/corpus'
      fullPath: '/corpus'
      preLoaderRoute: typeof CorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/mapping': {
      id: '/qa/mapping'
      path: '/qa/mapping'
      fullPath: '/qa/mapping'
      preLoaderRoute: typeof QaMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$jobHash': {
      id: '/opportunity/$jobHash'
      path: '/opportunity/$jobHash'
      fullPath: '/opportunity/$jobHash'
      preLoaderRoute: typeof OpportunityJobHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/deploy': {
      id: '/api/webhooks/deploy'
      path: '/api/webhooks/deploy'
      fullPath: '/api/webhooks/deploy'
      preLoaderRoute: typeof ApiWebhooksDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorpusRoute: CorpusRoute,
  DecisionsRoute: DecisionsRoute,
  DesignSystemRoute: DesignSystemRoute,
  FontSandboxRoute: FontSandboxRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ScrapedRoute: ScrapedRoute,
  WorkbenchRoute: WorkbenchRoute,
  OpportunityJobHashRoute: OpportunityJobHashRoute,
  QaMappingRoute: QaMappingRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiWebhooksDeployRoute: ApiWebhooksDeployRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
